apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.kuboard.cn/name: gin-mysqlbak-agent
  name: gin-mysqlbak-agent
  namespace: mysqlbak
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gin-mysqlbak-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gin-mysqlbak-agent
    spec:
      containers:
        - image: 'chenteng/gin-mysqlbak-agent:3.0.0'
          imagePullPolicy: IfNotPresent
          name: gin-mysqlbak-agent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/domain/config/config.ini
              name: baseconf
              subPath: config.ini
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        agent: 'true'
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: mysqlbak-agent-conf
          name: baseconf
